import { Geist, Geist_Mono } from "next/font/google";
import HeaderComponent from "./components/Header"
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col h-screen">
          <HeaderComponent />
          <main className="flex-grow overflow-hidden">{children}</main>
        </div>
      </body>
    </html>
  );
}
