import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { BsFillMoonStarsFill } from "react-icons/bs";


export default function Home() {
  return (
    <>
      <Head>
        <title>Ryan Riley Puzon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/ryfav.PNG" />
      </Head>
      <main className="bg-white px-10">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-2xl">juscuzryancan</h1>
            <ul className="flex items-center">
              <li><BsFillMoonStarsFill /></li>
              <li><a href="#">RESUME</a></li>
            </ul>
          </nav>
        </section>
      </main>
    </>
  )
}
