import { FaGithubSquare, FaLinkedin } from "react-icons/fa";
import Head from 'next/head';
import Image from 'next/image';
import { motion as m } from "framer-motion";
import running from "../public/running.png";

const Contacts = () => {

  return (
    <>
      <Head>
        <title>Ryan Riley Puzon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/ryfav.PNG" />
      </Head>
      <m.div 
        initial={{y: "100%"}}
        animate={{y: "0%"}}
        transition={{duration: 0.75, ease: "easeOut"}}
        exit={{opacity: 1}}
        id="skills"
        className="absolute top-0 left-0
        flex flex-col flex-grow
        bg-secondary
        h-screen w-screen
        pt-20 px-4
        dark:bg-primary dark:text-white"
      >
        <div className="snap-center">
          <div className="p-8 snap-center" id="contacts">
            <h2 className="flex justify-center text-3xl mb-4">Contacts</h2>
            <div className="flex justify-center">
              <div
                className="w-96 rounded"
              >
                <Image 
                  className="max-h-full rounded"
                  priority
                  alt="Finishing the big apple half marathon"
                  src={running}
                />
              </div>
              <div className="flex gap-4">
                <a 
                  href="https://github.com/juscuzryancan" 
                  target="_blank" 
                  rel="noreferrer"
                >
                  <FaGithubSquare className="h-16 w-16"/>
                </a>
                <a 
                  className=""
                  href="https://www.linkedin.com/in/ryanrileypuzon/" 
                  target="_blank" 
                  rel="noreferrer"
                >
                  <FaLinkedin className="h-16 w-16"/>
                </a>
              </div>
            </div>
          </div>
        </div>
      </m.div>
      </>
  );
}

export default Contacts;
